# Database properties
spring:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/facilpay-db-ec
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

# Database migration configuration
logging:
  level:
    liquibase: INFO

